language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get github.com/kardianos/govendor
  - go get github.com/stretchr/testify/assert
  - govendor sync

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
